### ISSUE TITLE
Splits used for reported results

### ISSUE THREAD

**Issue by Tianananana** [siyi-wind/AViT#2]
Thanks for your great work! From play.ipynb and the model weights released, you used the 4th fold for inference. Can I confirm if this is the fold that you used for the results you report in your paper? Thank you!

**Comment by siyi-wind** [comment]
Hi, thanks for the appreciation. In the paper, I used 5-fold cross-validation, so it's an average result on 5 models's results. The released model in the repository is trained on the 4th fold. Thus, you could get a very similar result as the paper, but may not be exactly the same. 

Datasets/create_dataset.py can help you get the same 4th-fold train and test results.

**Comment by Tianananana** [comment]
I see, thank you!
